apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-volume
  namespace: my-sensor-project 
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  resources:
    requests:
      storage: 1Gi
